language: node_js

node_js:
  - "6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm install
script:
  - npm test
branches:
  only: 
    - master
notifications:
  slack:
    secure: gyJ2jV8b6AvhOiFFErE1ndcFLINdYjD9DYtvXlsLOj39c7FV4sabj0mCMcYczv34knfT5VP946Vcot43Vb4EBUv7jByHD1cwD6ZFIgNyeLMHy/gt3Xrm8GOS2+Y2R6Bf0SlEhg1atz0ODSN0JPPrD4sys+0CWLHR+oLGK00SFGrv0SMZQL7eopYcLx+La9j+h6Js3emWquHACjlv+jVqHUguEjY2DZqhUkOAC50sRYRz19k+NwnhrGB+2xN3kC+U8rYNLnhE6v6CUpNLPMaNSF9qNFdVUIbRra/nxF447X3ASRGctENTY/MRn1evdXVPZDOTI0En0/yQTeeKAix69knAD9YSdkt/duRnur/XCKteZUtv3LtOibG7q9dSMauK/dTdQo34FxAVGb7TQB4zY5KAsx9Inif2hO48rKYnTfyy52FYW7oLgMRMSR3gCinfnnQfFiNchX4AP88RnvfXBOg6cBJI7dYEdivsghBMG7y2Zxom6izykr2eeYvGZMw//Fd2easCvr04PWH7fnRtvFL1PJzdf/nIdJUqZq6f6+C+45HPRnmh55zFtV/1IPjhnwjIu5e+FfOYU6TPf1VORYPZ9aNgOeNT4v8exK5EpkNPlydSUsfq0I666Xg9LfVS7Y5PWcSlxU0NGQEvHI/MYJqmjiuvyOPr1F8YHSg4GLE=
